In [1]:
#!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim

model = SentenceTransformer(
    "jinaai/jina-embeddings-v2-small-en", # switch to en/zh for English or Chinese
    trust_remote_code=True
)

# control your input sequence length up to 8192


embeddings_first_query = model.encode(['I just discovered the course. Can I join now?'])
print(embeddings_first_query)


/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[[-7.50172079e-01 -7.17383087e-01  5.75926661e-01  3.85590702e-01
  -1.39240563e-01 -4.59898412e-01  2.64997244e-01  3.42745751e-01
   1.50654037e-02 -1.08416945e-01  5.47503352e-01 -2.83161312e-01
  -4.78454411e-01 -9.73057151e-01  5.91714919e-01 -1.82749495e-01
  -8.65156576e-02 -2.96549827e-01 -1.39971673e-01 -3.80890429e-01
  -2.71147162e-01 -6.82426989e-02  3.14872086e-01 -5.08502647e-02
   8.22851539e-01 -8.71330678e-01 -7.17093766e-01  5.82157195e-01
   4.00452435e-01  7.58752823e-01 -4.51734960e-01  3.91243190e-01
   1.71669066e-01  8.54573995e-02 -3.03714544e-01  2.16495261e-01
   4.67889279e-01  1.73382789e-01 -3.55486453e-01 -3.47036511e-01
  -5.81855588e-02  2.91734576e-01  7.91352987e-01  1.05201095e-01
  -5.28488874e-01 -9.45520401e-02 -1.15149426e+00  3.30478370e-01
   6.93038180e-02  7.56270736e-02 -5.08152187e-01  5.37093461e-01
  -7.66221106e-01  4.14196461e-01  1.23974398e-01  5.21759033e-01
  -2.62948930e-01  1.65776953e-01 -3.68302137e-01  8.96729976e-02
   2.09843

In [2]:
embeddings.size


512

In [3]:
print(f'{embeddings.min():.2f}')

-1.15


In [4]:
embeddings_doc= model.encode(['Can I still join the course after the start date?'])


In [5]:
print(cos_sim(embeddings,embeddings_doc))

tensor([[0.9009]])


In [6]:
documents = [{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
  'section': 'General course-related questions',
  'question': 'Course - Can I follow the course after it finishes?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'You can start by installing and setting up all the dependencies and requirements:\nGoogle cloud account\nGoogle Cloud SDK\nPython 3 (installed with Anaconda)\nTerraform\nGit\nLook over the prerequisites and syllabus to see if you are comfortable with these subjects.',
  'section': 'General course-related questions',
  'question': 'Course - What can I do before the course starts?',
  'course': 'data-engineering-zoomcamp'},
 {'text': 'Star the repo! Share it with friends if you find it useful ❣️\nCreate a PR if you see you can improve the text or the structure of the repository.',
  'section': 'General course-related questions',
  'question': 'How can we contribute to the course?',
  'course': 'data-engineering-zoomcamp'}]
  

In [7]:
embeddings_documents=[]
for doc in documents:
    embeddings_documents.append(model.encode(doc['text']))

In [8]:
len(embeddings_documents)


5

In [9]:
import numpy as np

X = np.array(embeddings_documents)
             
print(X.shape)

(5, 512)


In [10]:
embeddings_query = embeddings.reshape(1, -1)

In [11]:
cos_sim(embeddings_documents,embeddings_query)


/usr/local/python/3.12.1/lib/python3.12/site-packages/sentence_transformers/util.py:55: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:254.)
  a = torch.tensor(a)


tensor([[0.7630],
        [0.8182],
        [0.8085],
        [0.7133],
        [0.7304]])

In [12]:
highest_index = int(np.argmax(cos_sim(embeddings_documents,embeddings_query)))


In [13]:
highest_index


1

In [14]:
embeddings_full_text=[]
for doc in documents:
    full_text = doc['question'] + ' ' + doc['text']
    embeddings_full_text.append(model.encode(full_text))

In [15]:
cos_sim(embeddings_full_text,embeddings_query)

tensor([[0.8515],
        [0.8437],
        [0.8408],
        [0.7755],
        [0.8086]])

In [16]:
highest_index = int(np.argmax(cos_sim(embeddings_documents,embeddings_query)))
highest_index

1

In [17]:
from fastembed import TextEmbedding
models=TextEmbedding.list_supported_models()

In [18]:
models


[{'model': 'BAAI/bge-base-en',
  'sources': {'hf': 'Qdrant/fast-bge-base-en',
   'url': 'https://storage.googleapis.com/qdrant-fastembed/fast-bge-base-en.tar.gz',
   '_deprecated_tar_struct': True},
  'model_file': 'model_optimized.onnx',
  'description': 'Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: necessary, 2023 year.',
  'license': 'mit',
  'size_in_GB': 0.42,
  'additional_files': [],
  'dim': 768,
  'tasks': {}},
 {'model': 'BAAI/bge-base-en-v1.5',
  'sources': {'hf': 'qdrant/bge-base-en-v1.5-onnx-q',
   'url': 'https://storage.googleapis.com/qdrant-fastembed/fast-bge-base-en-v1.5.tar.gz',
   '_deprecated_tar_struct': True},
  'model_file': 'model_optimized.onnx',
  'description': 'Text embeddings, Unimodal (text), English, 512 input tokens truncation, Prefixes for queries/documents: not so necessary, 2023 year.',
  'license': 'mit',
  'size_in_GB': 0.21,
  'additional_files': [],
  'dim': 768,
  'tasks': {}},
 {'model':

In [19]:

model_dims = {m['model']: m['dim'] for m in models}
print(model_dims)
smallest_model = min(model_dims,key=model_dims.get)
model_dims[smallest_model],smallest_model




{'BAAI/bge-base-en': 768, 'BAAI/bge-base-en-v1.5': 768, 'BAAI/bge-large-en-v1.5': 1024, 'BAAI/bge-small-en': 384, 'BAAI/bge-small-en-v1.5': 384, 'BAAI/bge-small-zh-v1.5': 512, 'mixedbread-ai/mxbai-embed-large-v1': 1024, 'snowflake/snowflake-arctic-embed-xs': 384, 'snowflake/snowflake-arctic-embed-s': 384, 'snowflake/snowflake-arctic-embed-m': 768, 'snowflake/snowflake-arctic-embed-m-long': 768, 'snowflake/snowflake-arctic-embed-l': 1024, 'jinaai/jina-clip-v1': 768, 'Qdrant/clip-ViT-B-32-text': 512, 'sentence-transformers/all-MiniLM-L6-v2': 384, 'jinaai/jina-embeddings-v2-base-en': 768, 'jinaai/jina-embeddings-v2-small-en': 512, 'jinaai/jina-embeddings-v2-base-de': 768, 'jinaai/jina-embeddings-v2-base-code': 768, 'jinaai/jina-embeddings-v2-base-zh': 768, 'jinaai/jina-embeddings-v2-base-es': 768, 'thenlper/gte-base': 768, 'thenlper/gte-large': 1024, 'nomic-ai/nomic-embed-text-v1.5': 768, 'nomic-ai/nomic-embed-text-v1.5-Q': 768, 'nomic-ai/nomic-embed-text-v1': 768, 'sentence-transformers/

(384, 'BAAI/bge-small-en')

In [20]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()


documents = []

for course in documents_raw:
    course_name = course['course']
    if course_name != 'machine-learning-zoomcamp':
        continue

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [21]:
from qdrant_client import QdrantClient, models

In [22]:
client = QdrantClient("http://localhost:6333") #connecting to local Qdrant instance

In [23]:
# Define the collection name
collection_name = "zoomcamp-rag"

# Create the collection with specified vector parameters
client.create_collection(
    collection_name=collection_name,
    vectors_config=models.VectorParams(
        size=384,  # Dimensionality of the vectors
        distance=models.Distance.COSINE  # Distance metric for similarity search
    )
)

UnexpectedResponse: Unexpected Response: 409 (Conflict)
Raw response content:
b'{"status":{"error":"Wrong input: Collection `zoomcamp-rag` already exists!"},"time":0.010113774}'

In [74]:
points = []
id = 0

for course in documents_raw:
    for doc in course['documents']:

        point = models.PointStruct(
            id=id,
            vector=models.Document(text = doc['question'] + ' ' + doc['text'], model=smallest_model), #embed text locally with "jinaai/jina-embeddings-v2-small-en" from FastEmbed
            payload={
                "text": doc['text'],
                "section": doc['section'],
                "course": course['course']
            } #save all needed metadata fields
        )
        points.append(point)

        id += 1

In [ ]:
client.upsert(
    collection_name=collection_name,
    points=points
)

In [78]:
def search(query, limit=1):

    results = client.query_points(
        collection_name=collection_name,
        query=models.Document( #embed the query text locally with "jinaai/jina-embeddings-v2-small-en"
            text=query,
            model=smallest_model
        ),
        limit=limit, # top closest matches
        with_payload=True #to get metadata in the results
    )

    return results

In [ ]:
result = search('I just discovered the course. Can I join now?')

In [ ]:
result